Add player
doro1129/maeDi pull request #7
Opened 2022-08-21 11:51 UTC by OhJunHyun

## Summary
* 카메라의 이동과 플레이어의 움직임, (시험용) 무기의 사용에 대해 다룹니다.   
   
## Description   
>### MoveCamera   
>* 카메라와 플레이어를 함께 움직이도록 해줍니다.
>* `cameraPosition`란에는 플레이어의 카메라를 넣어주세요.   
<br/>
   
>### Player Camera   
>* 마우스로 입력되는 x와 y 값을 받아 카메라를 회전시킵니다.   
>* `Orientation`란에는 플레이어의 방향을 저장하는 orientation을 넣어주세요.   
>* 시연 시 화면을 클릭하면 커서가 lock되며, 보이지 않게 됩니다. (esc를 통해 다시 보이게 할 수 있습니다.)   
>* 카메라의 최대각도는 -90°(하늘)와 90°(땅) 입니다.   
<br/>
   
>### FPSPlayer   
>* 플레이어의 전반적인 속성과 움직임을 나타냅니다.   
>* `Orientation`란에는 플레이어의 방향을 저장하는 orientation을 넣어주세요.   
>* `MoveSpeed`와 `RunSpeed`는 플레이어의 걷는 속도와 (shift를 누를 시) 달리는 속도를 나타냅니다.   
>* `GroundDrag`는 땅과의 저항력을 나타냅니다. 빙판처럼 미끄러지는 것을 방지합니다.   
>* `AirMultiplier`은 0.4의 값을 가지며 공중에서 가해지는 힘을 줄여주는 역할을 합니다.   
>* `What Is Ground`는 `whatIsGround`레이어와의 접촉을 `grounded`를 통해 boolean 값을 가지도록 해줍니다.   
>* `Update()`에서는 RayCast를 이용하여, 플레이어의 높이(키)의 1/2에 0.1을 더하여 `whatIsGround`레이어를 가지는 오브젝트의 존재를 판별하여 true와 false값을 가집니다.   
>* `MyInput()`에서는 수직과 수평 입력 값을 -1, 0, 1의 값으로 받습니다. 또한, space입력을 통해 점프할 수 있습니다.   
>* `MovePlayer()`에서는 `grounded`가 true인 경우, 수직과 수평 입력 값에 따라 상하좌우로 움직입니다. 또한, shift를 통해 속도를 달릴 수 있습니다.   
>* `SpeedControl()`에서는 속도를 수동적으로 제한하여 가속도가 높아지는 것을 방지합니다.   
>* `Jump()`에서는 `space`가 눌린 경우, 점프를 하게 합니다. (`Update()`에서 공중에 있는 경우에는 중력을 -60으로 하여 자연스럽게 내려오도록 했습니다. 필요한 경우 수정해주세요.) 
<br/>
   
>### Sword_Swing   
>* 시험용 무기인 knife에 데미지를 부여하며, 클릭 시, 주어진 애니메이션을 실행합니다.   
>* 마우스0 클릭 시, `is_Swung`이 true 값을 가지게 하며 `Sword_Swing` 애니메이션을 수행합니다. 또한, `Attack_time(쿨타임)`을 통해 `is_Swung`과 `is_Touched`를 false로 전환합니다.   
>* `enemy`태그를 가지는 물체와 Collider가 충돌할 경우, __시험적으로__ `Destroy()`를 수행합니다.
<br/>
   
>### WeaponSway   
>* 무기가 플레이어가 바라보는 시선에 고정될 수 있도록 하는 스크립트입니다.   
>* `Smooth`는 무기가 화면 전환 시, 자연스럽게 흔들리도록 합니다.   
>* `Multiplier`은 승수이며, 마우스 입력값에 곱해집니다.    
>* 무기의 회전량은 쿼터니언으로 계산되며 `Multiplier`로 곱해진 마우스 입력값 만큼 회전합니다.   
<br/><br/>
   
>## Camera Settings   
>1. 카메라의 위치를 나타낼 CameraHolder을 create empty로 생성하고, 안에 플레이어 카메라로 사용할 카메라를 추가해주세요.   
>2. 플레이어 카메라 아래에는 카메라와 무기를 함께 움직이게 하기 위한 WeaponHolder을 생성하고, 무기로 사용할 오브젝트를 추가해주세요.   
>3. 1번에서 생성한 CameraHolder에 `MoveCamera` 스크립트를 추가해주세요.
>4. 2번에서 생성한 플레이어 카메라에 `Player Camera` 스크립트를 추가해주세요. 
>>### Camera Setting (example)   
>>![image](https://user-images.githubusercontent.com/109288221/185786634-f0f6da69-8805-4af2-831a-aba571ffc662.png)

<br/><br/>
>## Player Settings   
>1. Create Empty로 플레이어의 전체를 담당할 오브젝트를 만들어주세요. 또한 RigidBody 컴포넌트를 추가해주세요.   
>2. 1번에 플레이어의 모델, 방향을 나타낼 orientation, 카메라의 위치를 나타낼 CameraPosition을 추가해주세요. 
>>### Player Setting (example)   
>>![image](https://user-images.githubusercontent.com/109288221/185786837-9394c9a3-9920-498b-95da-63f9884e680a.png)

<br/><br/>
>## Scene Settings   
>1. Camera Setting의 1번에서 생성한 Camera Holder의 Camera Position에 Player Setting 2번에서 만든 CameraPosition을 넣어주세요.   
>2. Camera Setting의 1번에서 생성한 플레이어 카메라(Player Camera)의 Orientation에 Player Setting 2번에서 만든 orientation을 넣어주세요.   
>>![image](https://user-images.githubusercontent.com/109288221/185788885-c922b941-89f9-4103-af6c-9fa6b895636d.png)
>>![image](https://user-images.githubusercontent.com/109288221/185788912-86f1dafd-79a4-47aa-b8e7-e79eb889cba9.png)
>3. `Orientation`에는 플레이어의 방향을 나타내는 `orientation`을 넣어주세요.   
>>![image](https://user-images.githubusercontent.com/109288221/185788967-115ae2c5-bd05-4dd1-9364-8b0f31d35e4d.png)   
>4. `Ground Check`의 `What Is Ground`에는 확인할 레이어(whatIsGround)를 선택해주세요.
>5. 플레이어 오브젝트에는 오브젝트에 맞는 Collider을 추가해주시고 `Material`에는 벽에 붙지 않게 해주는 `NoDrag` Physics Material을 넣어주세요.   

<br/><br/>
>## Animation Settings   
>1. `knife` 오브젝트에 `Animator`컴포넌트를 추가하여 `Sword_Swing` 컨트롤러를 넣어주세요.   
>>![image](https://user-images.githubusercontent.com/109288221/185789525-9392df2c-ee03-4571-8191-ff8e65d409e3.png)
>안될 시, 사진과 같이 해주세요.
>2. `CameraHolder` > `PlayerCamera`에 생성한 `WeaponHolder` 내부에 무기 오브젝트(knife)를 추가하여 `Sword_Swing`과 `Weapon Sway`를 추가해주세요.
>3. `Weapon Sway`의 `Smooth`의 값은 8, `Multiplier`은 4를 권장합니다. _**(제대로 작동하지 않는 오류를 발견했습니다. 수정 후 다시 올리도록 하겠습니다.)**_

<br/><br/>
>## Ohter Settings   
>1. 땅으로 취급하고 싶은 오브젝트에 `whatIsGround`레이어를 추가 후, 부여해주세요. 
>2. 적으로 취급하고 싶은 오브젝트에 `enemy` 태그를 추가 후, 부여해주세요.

2022-08-21 15:35 UTC, yejun614 commented
우선 작업 수고하셨습니다. 수정사항 알려 드립니다.

## 수정사항
1. `models/knife.obj` 파일이 누락되었습니다.
  - `models/knife.mtl` 파일은 OBJ파일의 Material입니다. 따라서 원본파일이 필요합니다.
2. Player Character의 Prefab 파일을 올려주시기 바랍니다.
  - 컴포넌트가 어떻게 조립되어야 하는지 자세한 설명은 감사합니다만 Prefab 파일을 직접 올려주시는 것이 좋겠습니다.
3. 소스코드는 같이 이야기하면서 수정 했으면 합니다.

2022-08-21 15:36 UTC, yejun614 requested changes
우선 작업 수고하셨습니다. 수정사항 알려 드립니다.

## 수정사항
1. `models/knife.obj` 파일이 누락되었습니다.
  - `models/knife.mtl` 파일은 OBJ파일의 Material입니다. 따라서 원본파일이 필요합니다.
2. Player Character의 Prefab 파일을 올려주시기 바랍니다.
  - 컴포넌트가 어떻게 조립되어야 하는지 자세한 설명은 감사합니다만 Prefab 파일을 직접 올려주시는 것이 좋겠습니다.
3. 소스코드는 같이 이야기하면서 수정 했으면 합니다.

2022-08-22 12:10 UTC, OhJunHyun commented
>## Changes   
>1. Player와 CameraHolder Prefabs 추가했습니다.   
>2. Sword로 되어있던 애니메이션 이름을 Knife로 수정했습니다.   
>3. `enemy`태그를 `Enemy`로 수정했습니다. (`Knife_Swing`코드 내부)

2022-08-26 15:15 UTC, doro1129 approved these changes
문제 없습니다

2022-08-26 15:16 UTC, OhJunHyun commented
## Changes

>* 변수이름 변경되었습니다.   
>> whatIsGround --> Tile   
>> PlayerHeight --> RaycastDistance

2022-08-27 12:31 UTC, yejun614 approved these changes
문제없습니다!

2022-08-27 12:40 UTC, yejun614 commented
해당 Branch는 5d40231 에서 분기되었으나 `Tile` Layer을 사용하기 위해서 `main` Branch 에서 분기된 임시 Branch로 Rebase 되었습니다. 때문에 이전 커밋의 시점이 변경되었으니 참고 바랍니다.

2022-08-27 13:06 UTC, merged